### ISSUE TITLE
Docker Not work

### ISSUE THREAD

**Issue by DonMonro** [DerekChia/colab-vscode#1]
when i run this and try install docker on VSCode its installed but not working, is there anyway to fix this?

**Comment by DerekChia** [comment]
@DonMonro you will need to use `udocker` instead of `docker`. Here's how you can do it - https://stackoverflow.com/a/78282911/1305959

<img width="711" alt="image" src="https://github.com/DerekChia/colab-vscode/assets/1457728/07df7522-2616-4f01-b691-a0071e3b9a62">

**Comment by DonMonro** [comment]
it's not full functionality and don't work in most expert usage
why you close this even ?

**Comment by DerekChia** [comment]
@DonMonro I've already provided a workaround, and that's through the use of [udocker](https://github.com/indigo-dc/udocker).

**Comment by DonMonro** [comment]
Chinese kids ...

**Comment by DerekChia** [comment]
@DonMonro maybe you could be helpful and expand on what you mean by "not full functionality" and "expert usage"?
